spring.application.name=shiptrack

spring.thymeleaf.cache=false 

spring.datasource.url=jdbc:mysql://localhost:3306/shiptrack_db
spring.datasource.username=root
spring.datasource.password=A7mad@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
server.error.whitelabel.enabled=false  
